name: Schedule Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule the workflow to run daily at midnight (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up R environment
        uses: r-lib/actions/setup-r@v1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run R script
        run: Rscript script.R  # Replace "script.R" with the name of your R script file

